let S={g:[],e:[],i:[]},sb,started=false;const $=id=>document.getElementById(id);
const MN='Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ');const mon=a=>[...new Set(a)].sort(),allM=()=>mon([...S.g.map(key),...S.e.map(e=>e[0])]);
const lab=m=>MN[+m.slice(2)-1]+" '"+m.slice(0,2),D=s=>new Date(2000+ +s.slice(0,2),+s.slice(2,4)-1,+s.slice(4,6));
const nt=b=>Math.round((D(b[2])-D(b[1]))/864e5),sum=(a,f)=>a.reduce((s,x)=>s+f(x),0),R=n=>(n<0?'-':'')+'₹'+Math.abs(Math.round(n)).toLocaleString('en-IN');
const fd=s=>D(s).toLocaleDateString('en-IN',{day:'numeric',month:'short'}),dt=v=>v.replace(/-/g,'').slice(2);
let tab=location.hash.slice(1)||'dash',fm='all';
const key=b=>b[2].slice(0,4); // revenue always belongs to the CHECK-OUT month
function st(m){const bs=S.g.filter(b=>key(b)==m),ex=S.e.filter(e=>e[0]==m),inc=sum(bs,b=>b[5]),exp=sum(ex,e=>e[3]),n=sum(bs,nt),dim=new Date(2000+ +m.slice(0,2),+m.slice(2),0).getDate();
return{m,bk:bs.length,n,inc,exp,p:inc-exp,occ:n/dim,adr:n?sum(bs,b=>b[4])/n:0}}
const pc=(v,d=1)=>(v*100).toFixed(d)+'%',cl=v=>v<0?'neg':'pos';
function paid(w){const h=e=>e[4]==w?e[3]:e[4]=='Both'?e[3]/2:0;return sum(S.i,i=>i[3]==w?i[2]:0)+sum(S.e,h)}
function dash(){const A=allM().map(st),act=A.filter(x=>x.bk||x.exp),inc=sum(A,x=>x.inc),ox=sum(A,x=>x.exp),inv=sum(S.i,i=>i[2]),ex=ox+inv,net=inc-ex,op=inc-ox,mx=Math.max(1,...A.map(x=>Math.max(x.inc,x.exp)));const d0=new Date(),cur=String(d0.getFullYear()).slice(2)+String(d0.getMonth()+1).padStart(2,'0');let H=A.filter(x=>x.bk&&x.m<cur);if(!H.length)H=A.filter(x=>x.bk);const hn=H.length||1,am=sum(H,x=>x.p)/hn,ae=sum(H,x=>x.exp)/hn,tn=sum(H,x=>x.n),npn=tn?sum(H,x=>x.inc)/tn:0,left=Math.max(0,inv-op),best=H.length?lab(H.reduce((a,b)=>b.p>a.p?b:a).m):'–';
const cats={};S.e.forEach(e=>cats[e[1]||'Other']=(cats[e[1]||'Other']||0)+e[3]);const cm=Math.max(1,...Object.values(cats));
return`<div class="g"><div class="c k"><small>Total income</small><b>${R(inc)}</b></div><div class="c k"><small>Expenses incl. investment</small><b>${R(ex)}</b></div><div class="c k"><small>Net profit</small><b class="${cl(net)}">${R(net)}</b></div><div class="c k"><small>Margin</small><b class="${cl(net)}">${inc?pc(net/inc):'0%'}</b></div></div>
<div class="c"><h3>Investment recovered: ${R(op)} of ${R(inv)} (${pc(Math.max(0,op)/(inv||1),0)})</h3><div class="bar"><i style="width:${Math.min(100,Math.max(0,op)/(inv||1)*100)}%"></i></div></div>
<h3 style="margin:4px 0 10px">Planning metrics <small style="color:var(--mut);font-weight:400">· based on completed months with bookings</small></h3><div class="g">${[['Avg monthly profit',R(am)],['Months to recover investment',left?(am>0?(left/am).toFixed(1):'–'):'Recovered ✓'],['Net earned / night',R(npn)],['Break-even occupancy',pc(npn?ae/npn/30:0,0)],['Avg stay',(tn/(sum(H,x=>x.bk)||1)).toFixed(1)+' nights'],['Best month',best]].map(([a,b])=>`<div class="c k"><small>${a}</small><b style="font-size:20px">${b}</b></div>`).join('')}</div>
<div class="c"><h3>Income <span class="pos">●</span> vs expenses <span style="color:var(--acc)">●</span></h3><div class="ch">${act.map(x=>`<div><p><i style="height:${x.inc/mx*100}%" title="${R(x.inc)}"></i><i style="height:${x.exp/mx*100}%" title="${R(x.exp)}"></i></p>${lab(x.m)}</div>`).join('')}</div></div>
<div class="c"><h3>Monthly performance</h3><div class="tw"><table><tr><th>Month<th class=r>Bookings<th class=r>Nights<th class=r>Occupancy<th class=r>Avg rate<th class=r>Income<th class=r>Expenses<th class=r>Profit<th class=r>Margin</tr>${act.map(x=>`<tr><td><b>${lab(x.m)}</b><td class=r>${x.bk}<td class=r>${x.n}<td class=r>${pc(x.occ,0)}<td class=r>${R(x.adr)}<td class=r>${R(x.inc)}<td class=r>${R(x.exp)}<td class="r ${cl(x.p)}">${R(x.p)}<td class=r>${x.inc?pc(x.p/x.inc,0):'–'}</tr>`).join('')}</table></div></div>
<div class="g"><div class="c"><h3>Spend by category</h3>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="margin-bottom:9px;display:flex;justify-content:space-between"><span>${k}</span><b>${R(v)}</b></div><div class="bar" style="margin:-6px 0 10px"><i style="width:${v/cm*100}%"></i></div>`).join('')}</div>
<div class="c"><h3>Partner contributions</h3>${['Vedant','Shriya'].map(w=>`<div class="k" style="margin-bottom:10px"><small>${w} paid (investment + expenses)</small><b>${R(paid(w))}</b></div>`).join('')}<small style="color:var(--mut)">'Both' expenses count half each.</small></div></div>`}
function bk(){const L=S.g.map((b,i)=>[b,i]).filter(([b])=>fm=='all'||key(b)==fm).reverse(),mo=sel(mon(S.g.map(key)));
return`<div class="c"><h3>Log a booking</h3><div class="f"><label>Guest<input id=bn></label><label>Check-in<input id=bi type=date></label><label>Check-out<input id=bo type=date></label><label>Guests<input id=bg type=number value=2></label><label>Rate/night ₹<input id=br type=number></label><label>Discount ₹<input id=ba type=number value=0></label><label>Cleaning fee ₹<input id=bc type=number value=0></label><label>Airbnb fee %<input id=bf type=number step=0.1 value=15.5></label><label>Tax withheld %<input id=bt type=number step=0.1 value=5></label><button class=b onclick=addB()>Add</button></div><small style="color:var(--mut)">Gross = nights × rate − discount + cleaning · Net = gross − fee − tax. Set both % to 0 for offline bookings.</small></div>
<div class="c"><div class="f" style="justify-content:space-between"><h3>${L.length} bookings · ${R(sum(L,([b])=>b[5]))} net</h3>${mo}</div><div class="tw"><table><tr><th>Guest<th>Check-in<th>Check-out<th class=r>Nights<th class=r>Guests<th class=r>Gross<th class=r>Net<th></tr>${L.map(([b,i])=>`<tr><td>${b[0]}<td>${fd(b[1])}<td>${fd(b[2])}<td class=r>${nt(b)}<td class=r>${b[3]}<td class=r>${R(b[4])}<td class=r><b>${R(b[5])}</b><td><button class=x onclick="del('g',${i})">✕</button></tr>`).join('')}</table></div></div>`}
function sel(l){return`<select onchange="fm=this.value;render()"><option value=all>All months</option>${l.map(m=>`<option value=${m} ${fm==m?'selected':''}>${lab(m)}</option>`).join('')}</select>`}
function ex(){const L=S.e.map((e,i)=>[e,i]).filter(([e])=>fm=='all'||e[0]==fm).reverse(),cs=[...new Set(S.e.map(e=>e[1]||'Other'))];
return`<div class="c"><h3>Log an expense</h3><div class="f"><label>Date<input id=ed type=date></label><label>Category<input id=ec list=cl></label><datalist id=cl>${cs.map(c=>`<option>${c}`).join('')}</datalist><label>Description<input id=es></label><label>Amount ₹<input id=ea type=number></label><label>Paid by<select id=ep><option>Shriya<option>Vedant<option>Both</select></label><button class=b onclick=addE()>Add</button></div></div>
<div class="c"><div class="f" style="justify-content:space-between"><h3>${R(sum(L,([e])=>e[3]))} spent</h3>${sel(mon(S.e.map(e=>e[0])))}</div><div class="tw"><table><tr><th>Month<th>Category<th>Description<th>Paid by<th class=r>Amount<th></tr>${L.map(([e,i])=>`<tr><td>${lab(e[0])}<td>${e[1]||'Other'}<td>${e[2]}<td>${e[4]||''}<td class=r><b>${R(e[3])}</b><td><button class=x onclick="del('e',${i})">✕</button></tr>`).join('')}</table></div></div>`}
function iv(){return`<div class="c"><h3>Add setup cost</h3><div class="f"><label>Item<input id=ii></label><label>Category<input id=ic></label><label>Amount ₹<input id=ia type=number></label><label>Paid by<select id=ip><option>Vedant<option>Shriya</select></label><button class=b onclick=addI()>Add</button></div></div>
<div class="c"><h3>Total investment ${R(sum(S.i,i=>i[2]))}</h3><div class="tw"><table><tr><th>Item<th>Category<th>Paid by<th class=r>Amount<th></tr>${S.i.map((i,x)=>`<tr><td>${i[0]}<td>${i[1]}<td>${i[3]}<td class=r><b>${R(i[2])}</b><td><button class=x onclick="del('i',${x})">✕</button></tr>`).join('')}</table></div></div>`}
const T={dash:['Dashboard',dash],bk:['Bookings',bk],ex:['Expenses',ex],iv:['Investment',iv]};
function render(){if(fm!='all'&&!allM().includes(fm))fm='all';$('nav').innerHTML=Object.entries(T).map(([k,v])=>`<button class="${tab==k?'on':''}" onclick="go('${k}')">${v[0]}</button>`).join('');$('app').innerHTML=T[tab][1]()}
function go(k){tab=k;fm='all';location.hash=k;render()}
const v=i=>$(i).value,pass=()=>localStorage.getItem('an_pass')||'',ymd=d=>d.slice(2,4)+d.slice(5,7)+d.slice(8,10);
async function load(){let d;try{d=await(await fetch(CONFIG.scriptUrl+'?key='+encodeURIComponent(pass()))).json()}catch(e){return toast('Could not reach Google Sheet')}
if(d.error=='unauthorized'){localStorage.removeItem('an_pass');started=false;return loginView('Wrong passcode')}if(d.error)return toast('Error: '+d.error);
const cmp=(a,c)=>a[1]<c[1]?-1:a[1]>c[1]?1:0;
S.g=d.bookings.map(x=>[x.guest,ymd(x.check_in),ymd(x.check_out),x.guests,x.gross,x.net,{row:x.row,guest:x.guest}]).sort(cmp);
S.e=d.expenses.map(x=>[x.month,x.category,x.description,x.amount,x.paid_by,x.date?ymd(x.date):'',{sheet:x.sheet,row:x.row,amount:x.amount,description:x.description}]).sort((a,c)=>a[0]+a[5]<c[0]+c[5]?-1:1);
S.i=d.investments.map(x=>[x.item,x.category,x.amount,x.paid_by,{row:x.row,item:x.item,amount:x.amount}]);render()}
async function run(b){toast('Saving to Google Sheet…');let r;try{r=await(await fetch(CONFIG.scriptUrl,{method:'POST',body:JSON.stringify({key:pass(),...b})})).json()}catch(e){return alert('Could not reach Google Sheet – nothing was saved')}
if(r.error)return alert('Could not save: '+r.error);await load();toast('Saved to Google Sheet ✓')}
function addB(){const i=v('bi'),o=v('bo');if(!v('bn')||!i||!o||!+v('br'))return alert('Add guest, dates and rate');if(o<=i)return alert('Check-out must be after check-in');run({action:'addBooking',guest:v('bn').trim(),check_in:i,check_out:o,guests:+v('bg')||2,rate:+v('br'),adj:+v('ba')||0,cleaning:+v('bc')||0,fee_pct:+v('bf')||0,tax_pct:+v('bt')||0})}
function addE(){if(!v('ed')||!+v('ea'))return alert('Add date and amount');run({action:'addExpense',date:v('ed'),category:v('ec')||'Other',description:v('es'),amount:+v('ea'),paid_by:v('ep')})}
function addI(){if(!v('ii')||!+v('ia'))return alert('Add item and amount');run({action:'addInvestment',item:v('ii'),category:v('ic')||'Misc',amount:+v('ia'),paid_by:v('ip')})}
function del(k,i){if(confirm('Delete this entry?'))run({action:{g:'delBooking',e:'delExpense',i:'delInvestment'}[k],...S[k][i].at(-1)})}
function toast(m){const t=$('t');t.textContent=m;t.classList.add('s');clearTimeout(toast.h);toast.h=setTimeout(()=>t.classList.remove('s'),1600)}
function dl(name,txt,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type}));a.download=name;a.click()}
const stamp=()=>new Date().toISOString().slice(0,10);
function exportJ(){dl('amber-nest-backup-'+stamp()+'.json',JSON.stringify(S),'application/json')}
function exportC(){const q=v=>'"'+String(v).replace(/"/g,'""')+'"',rows=[['BOOKINGS'],['Guest','Check-in','Check-out','Nights','Guests','Gross','Net'],...S.g.map(b=>[b[0],b[1],b[2],nt(b),b[3],b[4],b[5]]),[],['EXPENSES'],['Month','Category','Description','Paid by','Amount'],...S.e.map(e=>[e[0],e[1],e[2],e[4],e[3]]),[],['INVESTMENT'],['Item','Category','Paid by','Amount'],...S.i.map(i=>[i[0],i[1],i[3],i[2]])];dl('amber-nest-'+stamp()+'.csv',rows.map(r=>r.map(q).join(',')).join('\n'),'text/csv')}


const shell=h=>{$('nav').innerHTML='';$('app').innerHTML=h};
function loginView(m){shell('<div class="c" style="max-width:360px;margin:40px auto"><h3>Enter passcode</h3><div class="f" style="flex-direction:column;align-items:stretch"><label>Passcode<input id=lp type=password onkeydown="if(event.key==\'Enter\')unlock()"></label><button class=b onclick=unlock()>Open</button><small class=neg>'+(m||'')+'</small></div></div>')}
function unlock(){if(!v('lp'))return;localStorage.setItem('an_pass',v('lp'));start()}
function out(){localStorage.removeItem('an_pass');started=false;loginView()}
function start(){if(!pass())return loginView();shell('<p style="color:var(--mut)">Loading from your Google Sheet…</p>');load();if(!started){started=true;setInterval(()=>pass()&&document.visibilityState=='visible'&&load(),30000);document.addEventListener('visibilitychange',()=>{pass()&&document.visibilityState=='visible'&&load()})}}
if(typeof CONFIG=='undefined'||!CONFIG.scriptUrl||CONFIG.scriptUrl.includes('YOUR-'))shell('<div class="c"><h3>Setup needed</h3>Paste your Apps Script web app URL into <b>config.js</b> (see README).</div>');else start();
